export enum TagCodes {
  GRAO_DIRETO = 'GRAO_DIRETO',
  TECNOLOGIA = 'TECNOLOGIA',
  AGRONEGOCIO = 'AGRONEGOCIO',
  CICD = 'CICD',
  DEVOPS = 'DEVOPS',
  AGILIDADE = 'AGILIDADE',
  NOSQL = 'NOSQL',
  BANCO_DE_DADOS = 'BANCO_DE_DADOS',
  ESCALABILIDADE = 'ESCALABILIDADE',
  KUBERNETES = 'KUBERNETES',
  CONTEINERES = 'CONTEINERES',
  ORQUESTRACAO = 'ORQUESTRACAO',
  SERVERLESS = 'SERVERLESS',
  SEGURANCA = 'SEGURANCA',
  CLOUD = 'CLOUD',
  COLABORACAO = 'COLABORACAO',
  TIMES_DISTRIBUIDOS = 'TIMES_DISTRIBUIDOS',
  FRONTEND = 'FRONTEND',
  FRAMEWORKS = 'FRAMEWORKS',
  REACT = 'REACT',
  INOVACAO = 'INOVACAO',
}

export const TagLabels: Record<string, string> = {
  GRAO_DIRETO: 'Grão Direto',
  TECNOLOGIA: 'tecnologia',
  AGRONEGOCIO: 'agronegócio',
  CICD: 'CI/CD',
  DEVOPS: 'DevOps',
  AGILIDADE: 'agilidade',
  NOSQL: 'NoSQL',
  BANCO_DE_DADOS: 'banco de dados',
  ESCALABILIDADE: 'escalabilidade',
  KUBERNETES: 'Kubernetes',
  CONTEINERES: 'contêineres',
  ORQUESTRACAO: 'orquestração',
  SERVERLESS: 'serverless',
  SEGURANCA: 'segurança',
  CLOUD: 'cloud',
  COLABORACAO: 'colaboração',
  TIMES_DISTRIBUIDOS: 'times distribuídos',
  FRONTEND: 'frontend',
  FRAMEWORKS: 'frameworks',
  REACT: 'React',
  INOVACAO: 'inovação',
};
